name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      component:
        description: "Component to rollback"
        required: true
        type: choice
        options:
          - frontend
          - backend
      version:
        description: "Backup file name"
        required: true

jobs:
  rollback:
    runs-on: self-hosted

    steps:

      - name: Validate Backup
        shell: powershell
        run: |
          if (!(Test-Path 'C:\backups\${{ github.event.inputs.version }}')) { exit 1 }

      - name: Rollback Frontend
        if: ${{ github.event.inputs.component == 'frontend' }}
        shell: powershell
        run: |
          Remove-Item -Recurse -Force 'C:\dashboard\*'
          Expand-Archive -Path 'C:\backups\${{ github.event.inputs.version }}' -DestinationPath 'C:\dashboard' -Force
          iisreset

      - name: Rollback Backend
        if: ${{ github.event.inputs.component == 'backend' }}
        shell: powershell
        run: |
          iisreset /stop
          Remove-Item -Recurse -Force 'C:\deployment-api\*'
          Expand-Archive -Path 'C:\backups\${{ github.event.inputs.version }}' -DestinationPath 'C:\deployment-api' -Force
          iisreset /start
